### ISSUE TITLE
Your pre-trained weights link is disable

### ISSUE THREAD

**Issue by Biel-Hammer** [ChaoningZhang/Universal-Deep-Hiding#2]
hey gay, thanks for your sharing, but your pre-trained weights link is disable, may you try other way to update, such as  baiducloud

**Comment by Biel-Hammer** [comment]
ok it works

**Comment by wuxiaolianggit** [comment]
大佬，你好，怎么下载预训练模型啊，我也下载不了@ @Biel-Hammer @ChaoningZhang

**Comment by Map1e0823** [comment]
> ok it works

could you find the copy of pre-trained wights and share them on the baiducloud or somewhere else? the link didn't work again.
ty very much!
